version: 2
jobs:
  build:
    machine:
      docker_layer_caching: false
    working_directory: ~/repo
    steps:
      - checkout
      - run: mkdir test-reports

#      Get rid of dangling images
      - run: docker ps -a
      - run: docker images
      - run: docker rmi $(docker images -q --filter "dangling=true")

      - run: docker build -t noms .
      - run: docker run --name app noms
#       once application container finishes we can copy artifacts directly from it
      - run: docker cp app:/app/Results ./test-reports
      - store_artifacts:
          path: test-reports
          destination: tr1
#      - store_test_results:
#          path: test-reports/output.xml
#      - run: docker rm -f noms
#      - run: docker rm -f app
