version: 2
jobs:
  build:
    machine:
      docker_layer_caching: true
    working_directory: ~/repo
    steps:
      - checkout
#     - run: mkdir test-reports
      - run: mkdir test-results

      - run: docker build -t noms .
      - run: docker run --name app noms
      # once application container finishes we can copy artifacts directly from it
      - run: docker cp app:/app/Results ./test-results
      - store_artifacts:
          path: test-results
          destination: test-results
      - store_test_results:
          path: test-results
          destination: test-results

