version: 2
jobs:
  build:
    machine:
      docker_layer_caching: false
    working_directory: ~/repo
    steps:
      - checkout
      - run: mkdir test-reports

#      Get rid of dangling images
      - run: docker ps -a
      - run: docker image list

      - run: docker build -t noms .
      - run: docker run --name app noms
#       once application container finishes we can copy artifacts directly from it
      - run: docker cp app:/app/Results ./test-reports
      - store_artifacts:
          path: test-reports
          destination: tr1

#      remove all Exited containers
      - run: sudo docker ps -a | grep Exit | cut -d ' ' -f 1 | xargs docker rm

#      - store_test_results:
#          path: test-reports/output.xml
#      - run: docker rm -f noms
#      - run: docker rm -f app
